sudo: required
dist: trusty
language: node_js
node_js:
  - "node"
  - "6"
  - "4"

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -q
  - sudo apt-get install -y g++-4.9 bison flex libssl-dev libboost-dev libboost-system-dev libboost-filesystem-dev libboost-regex-dev

env:
  global:
    - CXX=g++-4.9
    - NODE_ENV=development
