sudo: required
dist: trusty
language: node_js
node_js:
  - "node"
  - "6"
  - "4"

before_install:
  - sudo apt-get install -y bison flex libssl-dev libboost-dev libboost-system-dev libboost-filesystem-dev libboost-regex-dev

env:
  global:
    - NODE_ENV=development
