sudo: required
dist: trusty
language: node_js
node_js:
  - "node"
  - "4"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
before_install:
  - sudo apt-get install -y bison flex libssl-dev libboost-dev libboost-system-dev libboost-filesystem-dev libboost-regex-dev
env:
  global:
    - CXX=g++-4.9
    - NODE_ENV=development
