language: node_js
node_js:
  - "node"
  - "4"
  - "0.12"
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y bison flex g++-4.9 libssl-dev libboost-dev libboost-system-dev libboost-filesystem-dev
